version: "3.8"
services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: node-backend
    ports:
      - "3001:3001"
    depends_on:
      - redis
    env_file: # 🔹 This line tells Docker to read from .env file
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
